// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVyUnSzkOtDD-idVrpZN5DmFeZ-gBkCuw',
    appId: '1:1073140998445:web:6789d15c6c8138668733a4',
    messagingSenderId: '1073140998445',
    projectId: 'serviceapp-dff9e',
    authDomain: 'serviceapp-dff9e.firebaseapp.com',
    storageBucket: 'serviceapp-dff9e.appspot.com',
    measurementId: 'G-T606QLPGCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-seXtLv5FriBL4H0pQxtCGHLCUU5cQA',
    appId: '1:1073140998445:android:4452a2f8e31372668733a4',
    messagingSenderId: '1073140998445',
    projectId: 'serviceapp-dff9e',
    storageBucket: 'serviceapp-dff9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXQ_U4qybt3C_IviHaD-wTFT5i_NqFBQ',
    appId: '1:1073140998445:ios:d0ece8cb03c2f2a18733a4',
    messagingSenderId: '1073140998445',
    projectId: 'serviceapp-dff9e',
    storageBucket: 'serviceapp-dff9e.appspot.com',
    iosClientId: '1073140998445-v25n8a2tjo890ddc1f3qdthotbm9giqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.service',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXQ_U4qybt3C_IviHaD-wTFT5i_NqFBQ',
    appId: '1:1073140998445:ios:fce864887fd89fcf8733a4',
    messagingSenderId: '1073140998445',
    projectId: 'serviceapp-dff9e',
    storageBucket: 'serviceapp-dff9e.appspot.com',
    iosClientId: '1073140998445-irj2p5d2q0j3ok7m7o8r05oog50ap6kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.service.RunnerTests',
  );
}
